Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1000

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
    Max: 80

AllCops:
  NewCops: enable
  Exclude:
    - Gemfile.lock
    - db/schema.rb
